<a href="https://colab.research.google.com/github/MisakiSF/Xor-from-Scratch/blob/main/XorFromScratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Devoir 3 : Multi layer Network XOR from scratch 
Realised by : EL MOUDNI SAFAE


In [ ]:
#importing liabrairies that we need
import numpy as np
import matplotlib.pyplot as plt
from random import randint
from mlxtend.plotting import plot_decision_regions

**The Activation function that we need**

In [ ]:

def sigmoid(x):
  return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
  return x * (1 - x)


**Build of the MultiLayerNN class**

In [ ]:
class MultiLayerNN:
  #the constractor for the initialisation of our Nn
  def __init__(self, inputNode, hidenNode,outputNode):
    
    self.inputNode=inputNode
    self.hidenNode=hidenNode
    self.outputNode=outputNode
    self.input_hiden=np.random.rand(hidenNode,inputNode)
    self.hiden_output=np.random.rand(outputNode,hidenNode)
    self.hiden_bias=np.random.rand(hidenNode,1)
    self.output_bias=np.random.rand(outputNode,1)
 
  #Etape 3 : Un fonction fit pour l'apprentissage
  def fit(self,X,Y,learning_rate=0.01,nmbr_iter=2000):

        self.learning_rate=learning_rate
        for i in range(nmbr_iter):
          index=randint(0,3)

          #La prediction 
          hiden=np.dot(self.input_hiden,X[index])
          hiden=hiden + self.hiden_bias
          hiden=np.array(list(map(sigmoid,hiden)))

          output=np.dot(self.hiden_output,hiden)
          output=output + self.output_bias
          output=np.array(list(map(sigmoid,output)))
          
          #La correction du hiden output -W
          output_Error=np.subtract(Y[index],output)
          gradian=np.array(list(map(sigmoid_derivative,output)))
          gradian=np.multiply(gradian,output_Error)
          gradian=np.dot(gradian,self.learning_rate)
          delta=np.dot(gradian,hiden.T)
          self.hiden_output=self.hiden_output+delta
          self.output_bias= self.output_bias+gradian
          hiden_Error=np.dot(self.hiden_output.T,output_Error)

          #La correction du
          hiden_gradian=np.array(list(map(sigmoid_derivative,hiden)))
          hiden_gradian=np.multiply(gradian,hiden_Error)
          hiden_gradian=np.dot(hiden_gradian,self.learning_rate)
          hiden_delta=np.dot(hiden_gradian,hiden.T)
          self.input_hiden=self.input_hiden+hiden_delta
          self.hiden_bias=self.hiden_bias+hiden_gradian
  
  #feed : Etape 4 :la fonction predict
  def predict(self,X):
    hiden=np.dot(self.input_hiden,X)
    hiden=hiden + self.hiden_bias
    hiden=np.array(list(map(sigmoid,hiden)))

    output=np.dot(self.hiden_output,hiden)
    output=output + self.output_bias
    output=np.array(list(map(sigmoid,output)))
    return output
   
    
  


**Test**

In [ ]:
X=[[[0],[0]],[[1],[0]],[[0],[1]],[[1],[1]]]
Y=[[0],[1],[1],[0]]
nn=MultiLayerNN(2,2,1)
nn.fit(X,Y,0.01,2000)

**Predection**

In [ ]:
print(nn.predict(X[0]))
print(nn.predict(X[1]))
print(nn.predict(X[2]))
print(nn.predict(X[3]))

[[0.54655771 0.53679832]]
[[0.54196162 0.5516975 ]]
[[0.54459709 0.50736562]]
[[0.53350387 0.51848772]]


**Creation** **model**

In [ ]:
model = MultiLayerNN(2,2,1)

**train** **model**

In [ ]:
model.fit(X, Y,0.001,1000)


**Visualize** **data** Here I got problem




